
server:
  port: 8087
spring:
  redis:
    database: 0
    host: 192.168.244.130
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 1000ms
